# fly.toml app configuration file generated for 4c-webviewer
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "4c-webviewer"
primary_region = "fra"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"
  jupyter_platform_dirs = "1"
  # Trame configuration
  TRAME_CLIENT_TYPE = "vue3"
  WSLINK_LAUNCHER_MODE = "none"
  PYTHONUNBUFFERED = "1"
  PYVISTA_OFF_SCREEN = "true"
  VTK_DEFAULT_RENDER_WINDOW_OFFSCREEN = "1"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  # Allow websocket connections
  [http_service.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512
