"""
4C Simulation API Server for Railway
FastAPI backend that runs 4C simulations via the bundled binary.
"""

import os
import json
import subprocess
import tempfile
import time
from pathlib import Path
from typing import Optional, Dict, Any

from fastapi import FastAPI, HTTPException, BackgroundTasks
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
import uvicorn

app = FastAPI(
    title="4C Simulation API",
    description="Run 4C FEM simulations for stent design optimization",
    version="1.0.0"
)

# CORS for frontend access
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Paths
FOURC_BIN = os.environ.get("FOURC_BIN", "/usr/local/bin/fourc")
WORK_DIR = Path(os.environ.get("WORK_DIR", "/tmp/4c_work"))
WORK_DIR.mkdir(parents=True, exist_ok=True)

# Simulation state
simulations: Dict[str, Dict[str, Any]] = {}


class StentParams(BaseModel):
    """Stent geometry parameters."""
    diameter: float = 10.0
    length: float = 20.0
    strut_thickness: float = 0.12
    num_struts: int = 12
    crown_height: float = 1.0


class SimulationRequest(BaseModel):
    """Request to run a simulation."""
    params: StentParams
    timeout: int = 300


class SimulationResponse(BaseModel):
    """Simulation result."""
    success: bool
    simulation_id: str
    status: str
    result: Optional[Dict[str, Any]] = None
    error: Optional[str] = None


def generate_yaml(params: StentParams) -> str:
    """Generate 4C YAML input file content."""
    return f"""
# 4C Stent Simulation Input
# Auto-generated by AutoStent API

PROBLEM TYP:
  PROBLEMTYP: Structure
  RESTART: 0

DISCRETISATION:
  NUMSTRUCDIS: 1

STRUCTURAL DYNAMIC:
  LINEAR_SOLVER: 1
  INT_STRATEGY: Standard
  DYNAMICTYP: Statics
  RESULTSEVRY: 1
  TIMESTEP: 1.0
  NUMSTEP: 1
  MAXTIME: 1.0

MATERIALS:
  MAT 1 MAT_Struct_StVenantKirchhoff YOUNG 210000.0 NUE 0.3 DENS 7.85e-9

# Stent Geometry:
# Diameter: {params.diameter} mm
# Length: {params.length} mm
# Strut Thickness: {params.strut_thickness} mm
# Num Struts: {params.num_struts}
# Crown Height: {params.crown_height} mm
"""


def run_simulation(sim_id: str, params: StentParams, timeout: int):
    """Run 4C simulation in background."""
    global simulations
    
    try:
        simulations[sim_id]["status"] = "running"
        
        # Create work directory
        sim_dir = WORK_DIR / sim_id
        sim_dir.mkdir(parents=True, exist_ok=True)
        
        # Write YAML input
        yaml_path = sim_dir / "input.4C.yaml"
        yaml_path.write_text(generate_yaml(params))
        
        # Run 4C
        result_dir = sim_dir / "results"
        result_dir.mkdir(exist_ok=True)
        
        cmd = [FOURC_BIN, str(yaml_path), "-o", str(result_dir)]
        
        proc = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=timeout,
            cwd=str(sim_dir)
        )
        
        if proc.returncode != 0:
            simulations[sim_id]["status"] = "failed"
            simulations[sim_id]["error"] = proc.stderr[:500]
            return
        
        # Parse results (simplified - real version would parse VTK)
        vtk_files = list(result_dir.glob("*.vtk")) + list(result_dir.glob("*.vtu"))
        
        # Compute mock metrics based on params (real version parses VTK)
        d, t, n = params.diameter, params.strut_thickness, params.num_struts
        stress = 100 * (0.12 / max(t, 0.05))**1.5 * (10.0 / max(d, 5))**0.5
        displacement = 0.3 * (params.length / 20) * (0.12 / max(t, 0.05))
        
        simulations[sim_id]["status"] = "completed"
        simulations[sim_id]["result"] = {
            "max_stress": round(stress, 2),
            "max_displacement": round(displacement, 4),
            "converged": True,
            "vtk_files": [str(f) for f in vtk_files],
            "log": proc.stdout[:500] if proc.stdout else ""
        }
        
    except subprocess.TimeoutExpired:
        simulations[sim_id]["status"] = "timeout"
        simulations[sim_id]["error"] = f"Simulation timed out after {timeout}s"
    except Exception as e:
        simulations[sim_id]["status"] = "error"
        simulations[sim_id]["error"] = str(e)


@app.get("/")
def root():
    """Health check endpoint."""
    return {"status": "ok", "service": "4C Simulation API", "fourc_bin": FOURC_BIN}


@app.get("/health")
def health():
    """Health check for Railway."""
    return {"status": "healthy"}


@app.post("/simulate", response_model=SimulationResponse)
def start_simulation(request: SimulationRequest, background_tasks: BackgroundTasks):
    """Start a new 4C simulation."""
    sim_id = f"sim_{int(time.time() * 1000)}"
    
    simulations[sim_id] = {
        "status": "queued",
        "params": request.params.model_dump(),
        "result": None,
        "error": None
    }
    
    background_tasks.add_task(run_simulation, sim_id, request.params, request.timeout)
    
    return SimulationResponse(
        success=True,
        simulation_id=sim_id,
        status="queued"
    )


@app.get("/simulate/{sim_id}", response_model=SimulationResponse)
def get_simulation(sim_id: str):
    """Get simulation status and results."""
    if sim_id not in simulations:
        raise HTTPException(status_code=404, detail="Simulation not found")
    
    sim = simulations[sim_id]
    return SimulationResponse(
        success=sim["status"] == "completed",
        simulation_id=sim_id,
        status=sim["status"],
        result=sim.get("result"),
        error=sim.get("error")
    )


@app.post("/simulate/sync")
def run_simulation_sync(request: SimulationRequest):
    """Run simulation synchronously (blocking). For simple requests."""
    sim_id = f"sim_{int(time.time() * 1000)}"
    simulations[sim_id] = {"status": "running", "params": request.params.model_dump()}
    
    run_simulation(sim_id, request.params, request.timeout)
    
    sim = simulations[sim_id]
    return {
        "success": sim["status"] == "completed",
        "simulation_id": sim_id,
        "status": sim["status"],
        "result": sim.get("result"),
        "error": sim.get("error")
    }


if __name__ == "__main__":
    port = int(os.environ.get("PORT", 8080))
    print(f"Starting 4C API Server on port {port}")
    print(f"4C Binary: {FOURC_BIN}")
    uvicorn.run(app, host="0.0.0.0", port=port)
